import { componentDocs, getComponentsByCategory, getComponentStats, type ComponentDoc } from "./componentDocs";

/**
 * Generate markdown documentation for a single component
 */
export function generateComponentMarkdown(doc: ComponentDoc): string {
  let md = `# ${doc.name}\n\n`;
  
  md += `> ${doc.description}\n\n`;
  
  md += `| Property | Value |\n`;
  md += `|----------|-------|\n`;
  md += `| **Category** | ${doc.category} |\n`;
  md += `| **File Path** | \`${doc.filePath}\` |\n`;
  md += `| **Lines of Code** | ${doc.linesOfCode.toLocaleString()} |\n`;
  md += `| **Exports** | ${doc.exports.join(", ")} |\n\n`;

  // Props section
  if (doc.props && doc.props.length > 0) {
    md += `## Props\n\n`;
    md += `| Name | Type | Required | Default | Description |\n`;
    md += `|------|------|----------|---------|-------------|\n`;
    doc.props.forEach(prop => {
      md += `| \`${prop.name}\` | \`${prop.type}\` | ${prop.required ? "✅" : "❌"} | ${prop.defaultValue || "-"} | ${prop.description} |\n`;
    });
    md += `\n`;
  }

  // Interfaces section
  if (doc.interfaces && doc.interfaces.length > 0) {
    md += `## Interfaces\n\n`;
    doc.interfaces.forEach(iface => {
      md += `### ${iface.name}\n\n`;
      md += `| Property | Type | Description |\n`;
      md += `|----------|------|-------------|\n`;
      iface.properties.forEach(prop => {
        md += `| \`${prop.name}\` | \`${prop.type}\` | ${prop.description} |\n`;
      });
      md += `\n`;
    });
  }

  // Methods section
  if (doc.methods && doc.methods.length > 0) {
    md += `## Methods\n\n`;
    doc.methods.forEach(method => {
      md += `### \`${method.name}\`\n\n`;
      md += `**Signature:** \`${method.signature}\`\n\n`;
      md += `${method.description}\n\n`;
      
      if (method.parameters.length > 0) {
        md += `**Parameters:**\n\n`;
        md += `| Name | Type | Description |\n`;
        md += `|------|------|-------------|\n`;
        method.parameters.forEach(param => {
          md += `| \`${param.name}\` | \`${param.type}\` | ${param.description} |\n`;
        });
        md += `\n`;
      }
      
      md += `**Returns:** \`${method.returns.type}\` - ${method.returns.description}\n\n`;
    });
  }

  // Usage example
  if (doc.usageExample) {
    md += `## Usage Example\n\n`;
    md += `\`\`\`tsx\n${doc.usageExample}\n\`\`\`\n\n`;
  }

  // Dependencies
  if (doc.dependencies.length > 0) {
    md += `## Dependencies\n\n`;
    doc.dependencies.forEach(dep => {
      md += `- \`${dep}\`\n`;
    });
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Generated by Vacuum Sewer Documentation System*\n`;

  return md;
}

/**
 * Generate a full API documentation markdown file
 */
export function generateFullDocumentation(): string {
  const stats = getComponentStats();
  const byCategory = getComponentsByCategory();
  
  let md = `# Vacuum Sewer ICM Components API Documentation\n\n`;
  md += `> Auto-generated documentation for all vacuum sewer modeling components\n\n`;
  
  // Table of contents
  md += `## Table of Contents\n\n`;
  md += `- [Overview](#overview)\n`;
  md += `- [Statistics](#statistics)\n`;
  Object.keys(byCategory).forEach(category => {
    const anchor = category.toLowerCase().replace(/\s+/g, "-");
    md += `- [${category}](#${anchor})\n`;
    byCategory[category].forEach(doc => {
      const compAnchor = doc.name.toLowerCase().replace(/\s+/g, "-");
      md += `  - [${doc.name}](#${compAnchor})\n`;
    });
  });
  md += `\n`;

  // Overview
  md += `## Overview\n\n`;
  md += `This documentation covers the React component library for vacuum sewer system modeling `;
  md += `and integration with InfoWorks ICM. The library provides tools for:\n\n`;
  md += `- Real-Time Control (RTC) code generation\n`;
  md += `- Network validation and diagnostics\n`;
  md += `- Cost estimation and design calculations\n`;
  md += `- 3D visualization\n`;
  md += `- Ruby script generation for ICM automation\n\n`;

  // Statistics
  md += `## Statistics\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Components | ${stats.totalComponents} |\n`;
  md += `| Total Lines of Code | ${stats.totalLinesOfCode.toLocaleString()} |\n`;
  md += `| Categories | ${stats.categories} |\n`;
  md += `| Average LOC per Component | ${stats.avgLinesPerComponent} |\n\n`;

  // Components by category
  Object.entries(byCategory).forEach(([category, docs]) => {
    md += `## ${category}\n\n`;
    
    docs.forEach(doc => {
      md += `### ${doc.name}\n\n`;
      md += `> ${doc.description}\n\n`;
      
      md += `**File:** \`${doc.filePath}\` | **LOC:** ${doc.linesOfCode}\n\n`;

      // Props table (if any)
      if (doc.props && doc.props.length > 0) {
        md += `#### Props\n\n`;
        md += `| Name | Type | Required | Description |\n`;
        md += `|------|------|----------|-------------|\n`;
        doc.props.forEach(prop => {
          md += `| \`${prop.name}\` | \`${prop.type}\` | ${prop.required ? "Yes" : "No"} | ${prop.description} |\n`;
        });
        md += `\n`;
      }

      // Key interfaces
      if (doc.interfaces && doc.interfaces.length > 0) {
        md += `#### Interfaces\n\n`;
        doc.interfaces.forEach(iface => {
          md += `**${iface.name}**\n\n`;
          md += `\`\`\`typescript\ninterface ${iface.name} {\n`;
          iface.properties.forEach(prop => {
            md += `  ${prop.name}: ${prop.type};\n`;
          });
          md += `}\n\`\`\`\n\n`;
        });
      }

      // Usage example
      if (doc.usageExample) {
        md += `#### Usage\n\n`;
        md += `\`\`\`tsx\n${doc.usageExample}\n\`\`\`\n\n`;
      }

      md += `---\n\n`;
    });
  });

  // Footer
  md += `## License\n\n`;
  md += `This documentation is generated from component source files.\n\n`;
  md += `---\n\n`;
  md += `*Last generated: ${new Date().toISOString()}*\n`;

  return md;
}

/**
 * Generate a README-style quick reference
 */
export function generateQuickReference(): string {
  const byCategory = getComponentsByCategory();
  
  let md = `# Vacuum Sewer Components Quick Reference\n\n`;
  
  Object.entries(byCategory).forEach(([category, docs]) => {
    md += `## ${category}\n\n`;
    md += `| Component | Description | LOC |\n`;
    md += `|-----------|-------------|-----|\n`;
    docs.forEach(doc => {
      md += `| **${doc.name}** | ${doc.description.slice(0, 60)}... | ${doc.linesOfCode} |\n`;
    });
    md += `\n`;
  });

  return md;
}

/**
 * Generate dependency documentation
 */
export function generateDependencyDocs(): string {
  let md = `# Component Dependencies\n\n`;
  
  const dependencyMap: Record<string, string[]> = {
    "ICMIntegration": ["RTCCodeGenerator", "RTCLogicSimulator", "RubyScriptViewer", "SawtoothVisualizer", "ModelDiagnostics", "NetworkValidator", "CostEstimator", "DesignCalculatorTool", "FrictionComparisonCalculator", "Network3DVisualizer"],
    "SystemOverview": ["InteractiveDiagrams", "TechnicalDiagrams", "ComponentsGuide"],
    "DesignCalculatorTool": ["DesignCalculator"]
  };

  md += `## Dependency Tree\n\n`;
  md += `\`\`\`\n`;
  
  Object.entries(dependencyMap).forEach(([parent, children]) => {
    md += `${parent}\n`;
    children.forEach((child, i) => {
      const isLast = i === children.length - 1;
      md += `${isLast ? "└──" : "├──"} ${child}\n`;
    });
    md += `\n`;
  });
  
  md += `\`\`\`\n\n`;

  md += `## Standalone Components\n\n`;
  const standalone = componentDocs.filter(doc => 
    !Object.values(dependencyMap).flat().includes(doc.name) &&
    !Object.keys(dependencyMap).includes(doc.name)
  );
  
  standalone.forEach(doc => {
    md += `- ${doc.name}\n`;
  });

  return md;
}

/**
 * Download markdown as a file
 */
export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
